experimental-features = nix-command flakes

substituters = https://mirror.sjtu.edu.cn/nix-channels/store https://cache.nixos.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShj= sakura-7:qNHQf6qgUywMz2hq/ymvgD8LIqzfh9/npQzz9pI4S8g=
